### ISSUE TITLE
Error when resize_ext4 function is being called

### ISSUE THREAD

**Issue by yogi81** [xbianonpi/xbian-package-initramfs#24]
See this line.

The code for resizing and converting is ALWAYS executed. This is not good :)

https://github.com/xbianonpi/xbian-package-initramfs/blob/45be6463d6191fd258a190e36a200b5837fd73bc/content/etc/xbian-initramfs/init#L249

**Comment by yogi81** [comment]
this function seems to fail:
https://github.com/xbianonpi/xbian-package-initramfs/blob/45be6463d6191fd258a190e36a200b5837fd73bc/content/etc/xbian-initramfs/cnvres-code.sh#L386

**Comment by yogi81** [comment]
I get arithmetic syntax error: 264

Please not, that i do not have btrfs file structure (root/@ and so on) but just a simple ext4 root file system

with all the data being in same partition

**Comment by yogi81** [comment]
and also please check the line 
export BLOCKNEW=$(($sectorNEW / ($TUNEBLOCKSIZE / 512) ))
https://github.com/xbianonpi/xbian-package-initramfs/blob/45be6463d6191fd258a190e36a200b5837fd73bc/content/etc/xbian-initramfs/cnvres-code.sh#L394

this could be a cause of arithmetic error, is everything set here?

**Comment by yogi81** [comment]
looks like sectorNEW is not set here

noresizesd on cmdline.txt is a workaround for now

**Comment by yogi81** [comment]
TUNEBLOCKSIZE also seems to be empty

**Comment by mkreisl** [comment]
Cloned sd-card installation to an ext4 partition (on external USB disk):
Used xbian-config command 6 (xbian copier) for that (source /dev/root, destination ext4:/dev/sda10 in my case)

Modified cmdline.txt and fstab
Important: **noconvertsd** parameter has to be added to cmdline

System booted without any issue. Can't see any problem in initramfs

Here my cmdline parameter
```
root@kmxbilr2 ~ # cat /proc/cmdline
8250.nr_uarts=0 bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  noconvertsd telnet zswap.enabled=1 zswap.compressor=lz4 console=tty1 root=PARTUUID=8cf2a8f3-0a rootflags=rw rootfstype=ext4 rootwait logo.nologo quiet noswap loglevel=0 partswap startevent=mountall selinux=0 splash nohdparm net.ifnames=0 biosdevname=0 --startup-event mountall
root@kmxbilr2 ~ #
```

**Comment by yogi81** [comment]
DId you do it based on the image: https://sourceforge.net/projects/xbian/files/release/XBian_Latest_rpi3.img.gz/download ?

**Comment by mkreisl** [comment]
> DId you do it based on the image: https://sourceforge.net/projects/xbian/files/release/XBian_Latest_rpi3.img.gz/download ?

No, I cloned my (up2date) sd-card installation to an ext4 partition on external USB disk

But of course, there is no difference between the XBian packages

Today I'm struggling with the resize_ext4 function, this does not work correctly you already posted.
But currently I have to repair my external USB disk before I can continue (FS btrfs and ext4 always gets randomly broken)

**Comment by yogi81** [comment]
by the way, does it also work after you reboot the system (with reboot menu entry). For me it starts to kodi, when i do reboot, then the system does not boot anymore and I do not see any outputs

**Comment by mkreisl** [comment]
> by the way, does it also work after you reboot the system (with reboot menu entry). For me it starts to kodi, when i do reboot, then the system does not boot anymore and I do not see any outputs

Yep, reboots always.

**Comment by mkreisl** [comment]
> TUNEBLOCKSIZE also seems to be empty

Found and fixed **resize_ext4** function

Need some more tests, if you want to apply the patch to your local installation, here is the patch
```
diff --git a/content/etc/xbian-initramfs/cnvres-code.sh b/content/etc/xbian-initramfs/cnvres-code.sh
index c2470d0..9fb31a3 100644
--- a/content/etc/xbian-initramfs/cnvres-code.sh
+++ b/content/etc/xbian-initramfs/cnvres-code.sh
@@ -154,14 +154,14 @@ get_root() {
         [ "$(btrfs fi show $CONFIG_root | grep -c devid)" -gt 1 ] && export RESIZEERROR=1
     fi
 
-    export DEV="${CONFIG_root%[0-9]}"
+    export DEV="${CONFIG_root%[0-9]}"; DEV="${DEV%[0-9]}"
     if [ ! -e ${DEV} ]; then
        export DEV=${DEV%p}
        export PARTdelim='p'
     else
        export PARTdelim=''
     fi
-    export PART=${CONFIG_root#${CONFIG_root%?}}
+    export PART=$(echo $CONFIG_root | grep -oE '[0-9]+$')
 
     return 0
 }
@@ -386,17 +386,17 @@ resize_part() {
 resize_ext4() {
     if [ "$RESIZEERROR" -eq "0" -a "$CONFIG_noresizesd" -eq '0' -a "$FSCHECK" = "ext4" ]; then
 
-        if [ "${FSCHECK}" = 'ext4' ]; then
-            # check if the partition needs resizing
-            TUNE2FS=$(/sbin/tune2fs -l ${CONFIG_root})
-            TUNEBLOCKSIZE=$(echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}')
-            TUNEBLOCKCOUNT=$(echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}')
-            export BLOCKNEW=$(($sectorNEW / ($TUNEBLOCKSIZE / 512) ))
-
-            # resize root partition
-            if [ "$TUNEBLOCKCOUNT" -lt "$BLOCKNEW" ]; then
-                test -n "$CONFIG_splash" && /usr/bin/splash --msgtxt="fs resize..."
-                test -n "$CONFIG_splash" || echo '
+        # check if the partition needs resizing
+        [ -e /etc/mtab ] || ln -s /proc/mounts /etc/mtab
+        TUNE2FS=$(/sbin/tune2fs -l ${CONFIG_root})
+        TUNEBLOCKSIZE=$(echo -e "${TUNE2FS}" | grep "Block size" | awk '{printf "%d", $3}')
+        TUNEBLOCKCOUNT=$(echo -e "${TUNE2FS}" | grep "Block count" | awk '{printf "%d", $3}')
+        export BLOCKNEW=$(($sectorNEW / ($TUNEBLOCKSIZE / 512) ))
+
+        # resize root partition
+        if [ "$TUNEBLOCKCOUNT" -lt "$BLOCKNEW" ]; then
+            test -n "$CONFIG_splash" && /usr/bin/splash --msgtxt="fs resize..."
+            test -n "$CONFIG_splash" || echo '
 8888888b.  8888888888  .d8888b.  8888888 8888888888P 8888888 888b    888  .d8888b.
 888   Y88b 888        d88P  Y88b   888         d88P    888   8888b   888 d88P  Y88b
 888    888 888        Y88b.        888        d88P     888   88888b  888 888    888
@@ -405,23 +405,22 @@ resize_ext4() {
 888 T88b   888              "888   888     d88P        888   888  Y88888 888    888
 888  T88b  888        Y88b  d88P   888    d88P         888   888   Y8888 Y88b  d88P
 888   T88b 8888888888  "Y8888P"  8888888 d8888888888 8888888 888    Y888  "Y8888P88';
-                e2fsck -p -f ${CONFIG_root}
-                /bin/mount -t ext4 ${CONFIG_root} "$CONFIG_newroot"
-                TUNEBLOCKCOUNT=$(/sbin/resize2fs ${CONFIG_root} | grep now | rev | awk '{print $3}' | rev)
-                if [ "$?" -eq '0' ]; then
-                    TUNEBLOCKCOUNT=${BLOCKNEW}
-                fi
-                umount ${CONFIG_root}
-
-                # check if parition was actually resized
-                if [ "${TUNEBLOCKCOUNT}" -lt "${BLOCKNEW}" ]; then
-                    echo "Resizing failed..."
-                    export RESIZEERROR="1"
-                else
-                    echo "Filesystem resized..."
-                fi
-                #e2fsck -p -f ${CONFIG_root}
+            e2fsck -p -f ${CONFIG_root}
+            /bin/mount -t ext4 ${CONFIG_root} "$CONFIG_newroot"
+            TUNEBLOCKCOUNT=$(/sbin/resize2fs ${CONFIG_root} | grep now | rev | awk '{print $3}' | rev)
+            if [ "$?" -eq '0' ]; then
+                TUNEBLOCKCOUNT=${BLOCKNEW}
+            fi
+            umount ${CONFIG_root}
+
+            # check if parition was actually resized
+            if [ "${TUNEBLOCKCOUNT}" -lt "${BLOCKNEW}" ]; then
+                echo "Resizing failed..."
+                export RESIZEERROR="1"
+            else
+                echo "Filesystem resized..."
             fi
+            #e2fsck -p -f ${CONFIG_root}
         fi
     fi
 }
```

First hunk fixes issue if root partition number is > 9, for example /dev/sda10 (in my case)
Rest fixes resize_ext4 function and redundant code removed
